FROM debian:12

RUN apt-get update && apt-get install -y nginx-full wget

WORKDIR /home
RUN wget https://github.com/nginx/nginx/raw/master/conf/mime.types
RUN cp mime.types /etc/nginx/

RUN rm /etc/nginx/sites-enabled/*

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 88 443

CMD ["nginx", "-g", "daemon off;"]