#image de node et sa version
FROM node:24-alpine

#Dossier de travail interne au container
WORKDIR /usr/src/app

#Installation du angular CLI 
RUN npm install -g @angular/cli

#Dossier de sortie pour le build
VOLUME [ "/dist" ]

#Commande par default: build Angular en production
CMD ["ng", "build", "--configuration", "production", "--output-path=/dist"]
